import os

# VM_FIXED_IP = os.getenv('VM_FIXED_IP')
VM_FIXED_IP = 'host.docker.internal'
VM_HOMEASSISTANT_PORT = 8123
TAPO_WEBHOOK_URL_COMMON_PART = f'http://{VM_FIXED_IP}:{VM_HOMEASSISTANT_PORT}/api/webhook/tapo-webhook'
TAPO_WEBHOOK_ON_URL = f'{TAPO_WEBHOOK_URL_COMMON_PART}-on'
TAPO_WEBHOOK_OFF_URL = f'{TAPO_WEBHOOK_URL_COMMON_PART}-off'