# Generated by Django 4.2.17 on 2024-12-16 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_message_text_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
