# Generated by Django 4.2.17 on 2024-12-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('interactions', '0004_zone_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('group', 'name')},
        ),
    ]
