# Generated by Django 4.2.17 on 2024-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='mock',
            field=models.BooleanField(default=False),
        ),
    ]
