# Generated by Django 4.2.17 on 2024-12-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_alter_notification_user_alter_notification_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('ENTRANCE', 'Entrance'), ('EXIT', 'Exit')]),
        ),
    ]
