# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder "./homeassistant", "/home/vagrant/code/DIT-thesis/app/ubuntu/homeassistant"
    config.ssh.insert_key = true
    # Use a bridged (public) network adapter as well as NAT (Default adapter 1) with a fixed ip
    config.vm.network "public_network", ip: "192.168.1.17"
    config.vm.network "forwarded_port", guest: 8123, host: 8124
  
    config.vm.provider "virtualbox" do |vb|
      vb.name = "DIT-Thesis"
      vb.gui = false
      vb.memory = 4096
      vb.cpus = 2
    end
  end